// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA57qVrNE5lSC5lvkxcjjhCx_q-obsM0E4',
    appId: '1:86126559638:web:5f2de8e8456bffb0bd5db7',
    messagingSenderId: '86126559638',
    projectId: 'diskarte-ai',
    authDomain: 'diskarte-ai.firebaseapp.com',
    storageBucket: 'diskarte-ai.firebasestorage.app',
    measurementId: 'G-GVTZ3RG2CW',
  );

}